anoma/namada-indexer

- Cargo.toml
- shared/src/id.rs
- shared/src/proposal.rs
something weird happen with the sdk
> upgrade to 0.37.0

- transactions/Dockerfile
add libpq5 to the 'transactions' dockerfile as in https://github.com/anoma/namada-indexer/pull/54
> Update transactions Dockerfile

- README.md
Add instructions to create the `.env` file
> docs: add env file instructions

- chain/src/services/namada.rs
- shared/src/ser.rs
- swagger-codegen.json
- swagger.yml
- webserver/src/response/governance.rs
- webserver/src/response/utils.rs
- fix proposal id
- add activationTime for proposals
- rename `data` in pagination props to `results`
> fix: minor fixes

- .env_sample
- README.md
- chain/run.sh
- docker-compose.yml
- governance/run.sh
- justfile
- parameters/run.sh
- pos/run.sh
- rewards/run.sh
- seeder/run.sh
- transactions/run.sh
- webserver/run.sh
Just a couple updates to make it more convenient to run the services in development:
* Update `run.sh` scripts to use the `.env` file
* Add `run-*` commands to the `justfile`
* Update the README accordingly
> Enhancement: run script and readme updates

- Cargo.toml
- chain/src/repository/pos.rs
> do not error on empty changeset

- orm/migrations/2024-06-12-140948_gas/up.sql
Reverts anoma/namada-indexer#150
> Revert "feat: increase gas limit for withdraw tx"

- webserver/src/repository/governance.rs
Resolves https://github.com/anoma/namada-interface/issues/1280 and  https://github.com/anoma/namada-indexer/issues/153
> feat: default proposals sorting

- shared/src/transaction.rs
> try to serialize tx, avoid unwrapping

- chain/src/repository/pos.rs
- shared/src/block.rs
> fix: delete rewards by both source and validator

- Cargo.toml
Needs to wait for dry run to upgrade to 0.46.0
> chore: update namada to 0.46.0

- chain/src/main.rs
- chain/src/repository/pos.rs
- chain/src/services/utils.rs
- orm/src/schema.rs
> fix: insert bonds and unbonds in chunks

- chain/src/main.rs
- chain/src/repository/balance.rs
- chain/src/repository/gov.rs
- chain/src/repository/mod.rs
- chain/src/repository/pos.rs
- chain/src/repository/utils.rs
- shared/src/tuple_len.rs
- adds insert votes in chunks
- refactors logic to use new macro
> feat: insert votes in chunks

- swagger.yml
Updating swagger yml to match latest indexer changes on health and ibc endpoints
> Fixing small issues on Swagger

- transactions/src/services/tx.rs
Fixes a bug for which ibc gas could end up being underestimated.
> Fixes ibc gas accounting

- transactions/src/main.rs
> fetch and upsert epoch

- docker-compose-db.yml
persistent postgres volume: configured postgres to use a named volume for data persistence
> fix: persistent Postgres volume

- .env.sample
- README.md
Aligning with Namada MASP Indexer = Consoicency.
> docs: update README & .env.sample

- webserver/src/repository/gas.rs
The gas estimates function previously used `ge` when filtering for the number of signatures and the tx size. This PR changes it to `between` and sets some predefined upper bounds (a scalar for the signatures and a percentage for the tx size): this should reduce the values of the `max` estimates we return to more appropriate ones
> Gas estimates upperbounds

- shared/src/block.rs
- shared/src/transaction.rs
> Fix balance changes of failing txs

- shared/src/transaction.rs
Closes https://github.com/anoma/namada-indexer/issues/368
> Fix tx batches aborting due to gas errors or atomicity

- chain/src/main.rs
- chain/src/repository/balance.rs
- chain/src/services/namada.rs
- orm/src/token.rs
- shared/src/block.rs
- shared/src/token.rs
- shared/src/utils.rs
- webserver/src/response/chain.rs
- webserver/src/service/chain.rs
> fix token supplies

- chain/src/main.rs
- chain/src/services/namada.rs
- shared/src/block.rs
- transactions/src/main.rs
- transactions/src/services/namada.rs
So we can deserialize txs when proposals activate
> feat(chain,transactions): re-query checksums on new epoch
